#%RAML 0.8
---
title: Compra venta de gatitos
version: v1
#baseUri: http:/localhost:8080/{version}/
baseUri: http://mocksvc.mulesoft.com/mocks/08923082-658e-41d9-a5e5-d1eacb438183
mediaType: application/json
schemas:
  - cats: !include cats.schema.json
  - cat: !include cat.schema.json
  - error: !include error.schema.json
resourceTypes:
  - collection: 
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName>>
          500:
            body:
              schema: error
              example: |                
                { 
                  "error" : {
                    "code" : "java.lang.NumberFormatException",
                    "messages" : "For input string: \"-1s01.2335314026465\"",
                    "status": 500
                   }
                }
                
      post:
        responses:
          200:
            body:
              schema: <<resourcePathName | !singularize>>
          
  - member:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName | !singularize>>
              
      put:
        responses:
          201:
            body:
              schema: <<resourcePathName>>
      delete:
        responses:
          304:
    

/cats:
  displayName: Gatitos
  description: Compra, venta y renta de gatitos
  type: collection
    
  /{catId}:
    description: Un gatito en especifico
    type: member
   
  
